### ISSUE TITLE
Squad Info Error

### ISSUE THREAD

**Issue by Cmdr-Mark** [pwestling/battlescribe-roster-parser#37]
**Describe the bug**
When using Num 1 on some of my squads in my 2k pts army gives the following error:
![image](https://user-images.githubusercontent.com/63992091/79712481-cbceb300-827f-11ea-8db9-9e35cff5314d.png)

**Expected behavior**
This should give something like this:
![image](https://user-images.githubusercontent.com/63992091/79712519-e9038180-827f-11ea-80a5-268a2bed284a.png)

**Upload the Roster**
Couldn't figure out how to make it a ZIP file so here's pastebin:
https://pastebin.com/4XMFFvNu

**Comment by pwestling** [comment]
This is a known issue I've been working on cracking, but it's proven very tough. I'll let you know when it's fixed, but in the mean time I think saving and reloading the table will let you open some additional sheets before it crashes again.

**Comment by pwestling** [comment]
I think this issue should be solved now. If you continue to see the issue, please create a new ticket for me. Thanks!

**Comment by Cmdr-Mark** [comment]
Looks like I'm still having the same problem, I was able to get one more unit tinted before getting the error
Thanks
